### ISSUE TITLE
JWT Authentication Failed - Manage Points

### ISSUE THREAD

**Issue by chrisrosa418** [oktadeveloper/okta-react-graphql-example#1]
When I navigate to the Manage Points section, I get a `Failure to Communicate with API` failure on the frontend, and on the backend, it shows `JWT Validation Failed!`

I have recreated my OKTA application and ensured I am using the correct clientID and issuer.

Any advice?

**Comment by chrisrosa418** [comment]
Further, I am getting the following error on the backend

`name: 'SigningKeyNotFoundError'`

It looks like its hitting the OKTA server but failing thereafter.

**Comment by mraible** [comment]
Make sure your issuer doesn’t have “-admin” in the URL. Also, it should have /oauth2/default on the end. Or, the ID of your authorization server if you created a custom one.

**Comment by chrisrosa418** [comment]
That did it, thanks for the quick response!

_CR
